PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/3f860280e5b68b6a55a039236dfbfa29b63e3ade

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/9d006171883937823b8a10613507d7c5825b81de) in current PX4/master (1f4b2d1d53c48f8041152dd2c906502062bbad2f)
https://github.com/PX4/NuttX/compare/9d006171883937823b8a10613507d7c5825b81de...3f860280e5b68b6a55a039236dfbfa29b63e3ade

3f860280e5 (HEAD, origin/master) arm/common: Fix nxstyle issue in arch/arm/src/common/up_checkstack.c
bc29b25983 arm/imx6: compile up_hostfs.c when CONFIG_ARM_SEMIHOSTING_HOSTFS equal true
d5905d5963 arch/arm: Fix linker error: undefined reference to `g_intstackalloc'
272a1460c5 Revert "tools/testbuild.sh: suppress lots of stdout log from configure.sh"
f6fc87bc36 tools/sethost.sh & tools/configure.c: When no make argument is passed, silence the make output.
9fdda58eca sim: Hide putenv
2e933102e1 sim: Hide getopt related globals
702d82d052 vpnkit: Add a config to specify the socket
12a97acaed vpnkit: Make this less verbose on connection errors
e4c8f5d767 esp32: Guard the binary generation with CONFIG_ESP32CORE_BINARY

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/f16a765ccaa9395250423c4498a9e31aac5a558d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (1f4b2d1d53c48f8041152dd2c906502062bbad2f)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...f16a765ccaa9395250423c4498a9e31aac5a558d

f16a765c (HEAD -> master, origin/master) examples: Fix the parallel build break (#138)
1511403f Revert "Don't generate .depend anymore"
f074d7f3 Makefile: let install depend on the target binary
258e0140 Revert "Ensure "build" before "install""
8a7ea169 Revert "examples/elf/tests: Ensure "build" before "install""
9394424b Revert "examples/sotest/lib: Fix dependency"
cc5ad09c Don't generate .depend anymore
6ddf3471 Move MAKE_template and SDIR_template to Make.defs (#135)
6e3a9a2e Call TESTANDREPLACEFILE instead of mv
7caef179 Fix the typo error